### ISSUE TITLE
Ability to multi-tag

### ISSUE THREAD

**Issue by LeDominik** [GoogleContainerTools/kaniko#217]
In our build-pipeline we always add 2 tags: One for the git hash and one with the branch and or tag for releases, etc... So for `docker build` we simply pass two tags and then push both.

I'm wondering if there's a way to support this model in Kaniko as well...BTW awesome tool!

**Comment by priyawadhwa** [comment]
Hey @LeDominik, you can pass in multiple destinations to push the image too by setting the `--destination` flag multiple times.

**Comment by LeDominik** [comment]
Oh cool, I didn't even try because for the build parameters it was clearly outlined in the help text 👍

**Comment by saschak094** [comment]
@priyawadhwa  I've tried to use multiple ```--destination``` flags, but our new build image is only tagged and pushed once.

**Comment by priyawadhwa** [comment]
Hey @saschak094 I rebuilt the executor image and this should work now.

**Comment by saschak094** [comment]
Hey @priyawadhwa just tried it with the newest image but we are still not able to push to multiple destinations

**Comment by priyawadhwa** [comment]
Hey @saschak094 , thanks for letting me know! I just changed how we release the executor image, so hopefully shouldn't face this problem again. Could you try again with the new :latest image?

**Comment by ypadlyak** [comment]
Hey @priyawadhwa, 
It does work for me. Thank you!

**Comment by d-sko** [comment]
Hello, I'm using kaniko in a GitLab CI Pipeline, which works fine with one tag, but with two destination flags I only get the tag of the last destination flag in the registry. Is something wrong with my command:
```
/kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG --destination $CI_REGISTRY_IMAGE:latest
```

**Comment by priyawadhwa** [comment]
Hey @d-sko what version of kaniko are you using?

**Comment by giulio1979** [comment]
Hi guys, I have same situation, on multiple destinations, only last one is reaching repository. We use gcr.io/kaniko-project/executor:debug image.

**Comment by callumd789** [comment]
@giulio1979 - did you anywhere when trying to set multiple destinations with the `gcr.io/kaniko-project/executor:debug` image?

**Comment by alinex** [comment]
@callumd789 it is working for me, see https://gitlab.com/alinex/docker-mkdocs/blob/master/.gitlab-ci.yml
