### ISSUE TITLE
Dockerfile in AWS Codecommit

### ISSUE THREAD

**Issue by rikirolly** [GoogleContainerTools/kaniko#2282]
Does someone successfully configured kaniko with AWS Codecommit?

**Comment by rikirolly** [comment]
I discovered the problem is not related to git pull but probably to the information contained in my repository.
Still don't know where the problem reside.

**Comment by rikirolly** [comment]
Probably e problem in go-git module:
[https://github.com/go-git/go-git/pull/111](https://github.com/go-git/go-git/pull/111)

**Comment by aaron-prindle** [comment]
It seems the issue you referenced was fixed in the go-git PR here:
https://github.com/go-git/go-git/pull/392

kaniko adopted go-git w/ the fix PR in it in the PR here - https://github.com/GoogleContainerTools/kaniko/pull/1885

**Comment by maragunde93** [comment]
I am facing the same issue with kaniko executor 1.9.1. Still not finding any solution

**Comment by markrin** [comment]
Was not able to find a way to handle this, so used a workaround: archive and push source code to s3 bucket, use s3 as context. Stupid, but works smoothly.
