### ISSUE TITLE
Build fails when FROM image AS alias has capital letters

### ISSUE THREAD

**Issue by BenHizak** [GoogleContainerTools/kaniko#770]
**Actual behavior**
Named build stages (FROM someimage as myname) fail when name begins with a Capital letter
Example:

1. `FROM python:3.7.2 AS library` ✔ builds successfully (note that there are no capital letters)
2. `FROM python:3.7.2 AS Library` ❌ fails (note that there is a capital letter)
Error shown
```
Downloading base image Library               
error building image: could not parse reference
ERROR
```
**Expected behavior**
When using named stages, capital letters should not break the build process
**To Reproduce**
Please see [this gist](https://gist.github.com/BenHizak/a792064af4dc49db07876815439aabbf)

**Comment by N4rm0** [comment]
@tejal29  PR #787 should fix this issue.

**Comment by tejal29** [comment]
Awesome! we should update to latest moby/buildkit

**Comment by antechrestos** [comment]
@N4rm0 you should report your fix in vendor code because currently the problem is stille [present](https://github.com/moby/buildkit/blob/master/frontend/dockerfile/instructions/parse.go#L298)

Upgrading to the latest moby/buildkit will not fix the issue

**Comment by antechrestos** [comment]
@tejal29 I implemented a small fix by implementing it in the resolution in order not to change third party library behaviour
